# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_SLEEP=y

#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

# macos logo open this config
#CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y

# バッテリーを数値（％）で表示する
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# WPM（タイピング速度）機能をONにする
CONFIG_ZMK_WPM=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# 画像（ロゴ）をオフにする
CONFIG_ZMK_WIDGET_LOGO_STATUS=n

# レイヤー名を表示する
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

